/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/authorize/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["auth.authorizeGoogle"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/callback/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["auth.callbackGoogle"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["authSession.me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["authSession.logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["authSession.refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/pending-jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["authSession.pendingJobs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/labels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["labels.listLabels"];
    put?: never;
    post: operations["labels.createLabel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/labels/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["labels.updateLabel"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/threads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["threads.listThreads"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/threads/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["threads.syncThreads"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthUser: {
      id: string & unknown;
      email: string & (unknown & unknown);
      displayName: string & (unknown & unknown);
      /** @enum {string} */
      role: "admin" | "user";
      primaryProvider: "google";
      createdAt: string;
      updatedAt: string;
    };
    UnauthorizedError: {
      /** @enum {string} */
      _tag: "UnauthorizedError";
    };
    AuthPersistenceError: {
      /** @enum {string} */
      _tag: "AuthPersistenceError";
      /** @enum {string} */
      message: "A database error occurred while processing authentication data.";
    };
    SessionNotFoundError: {
      /** @enum {string} */
      _tag: "SessionNotFoundError";
    };
    PendingPersistedJobCounts: {
      userInboxSyncCount: number;
      messageAutoLabelCount: number;
    };
    DatabaseUnavailableError: {
      /** @enum {string} */
      _tag: "DatabaseUnavailableError";
      /** @enum {string} */
      message: "Service temporarily unavailable.";
    };
    PermissionDeniedError: {
      /** @enum {string} */
      _tag: "PermissionDeniedError";
    };
    Label: {
      id: string & unknown;
      userId: string & unknown;
      name: string & (unknown & unknown);
      prompt: string | null;
      /** @enum {string} */
      type: "system" | "custom";
      isActive: boolean;
      createdAt: string;
      updatedAt: string;
    };
    LabelPersistenceError: {
      /** @enum {string} */
      _tag: "LabelPersistenceError";
      /** @enum {string} */
      message: "A database error occurred while processing labels.";
    };
    LabelAlreadyExistsError: {
      /** @enum {string} */
      _tag: "LabelAlreadyExistsError";
      name: string;
    };
    InboxPersistenceError: {
      /** @enum {string} */
      _tag: "InboxPersistenceError";
      /** @enum {string} */
      message: "A database error occurred while processing inbox data.";
    };
    LabelNotFoundError: {
      /** @enum {string} */
      _tag: "LabelNotFoundError";
    };
    InboxParticipant: {
      name:
        | {
            /** @enum {string} */
            _tag: "Some";
            value: string;
          }
        | {
            /** @enum {string} */
            _tag: "None";
          };
      email: string & (unknown & unknown);
    };
    InboxThreadLabel: {
      labelId: string & unknown;
      labelName: string;
    };
    InboxThread: {
      id: string & unknown;
      subject: string;
      snippet: string;
      lastMessageAt: string;
      messageCount: number;
      isUnread: boolean;
      lastMessageId: string & unknown;
      participants: components["schemas"]["InboxParticipant"][];
      labels: components["schemas"]["InboxThreadLabel"][];
    };
    InboxThreadListPage: {
      items: components["schemas"]["InboxThread"][];
      total: number;
    };
    InboxNotConnectedError: {
      /** @enum {string} */
      _tag: "InboxNotConnectedError";
    };
    InboxReauthorizationRequiredError: {
      /** @enum {string} */
      _tag: "InboxReauthorizationRequiredError";
    };
    InboxSyncError: {
      /** @enum {string} */
      _tag: "InboxSyncError";
      /** @enum {string} */
      message: "Inbox synchronization failed.";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "auth.authorizeGoogle": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            redirectUrl: string;
            state: string;
          };
        };
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "auth.callbackGoogle": {
    parameters: {
      query: {
        state: string;
        code?: string | null;
        error?: string | null;
        error_description?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description <No Content> */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "authSession.me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description AuthUser */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthUser"];
        };
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description UnauthorizedError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedError"];
        };
      };
      /** @description AuthPersistenceError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthPersistenceError"];
        };
      };
    };
  };
  "authSession.logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description <No Content> */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description SessionNotFoundError | UnauthorizedError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["SessionNotFoundError"]
            | components["schemas"]["UnauthorizedError"];
        };
      };
      /** @description AuthPersistenceError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["AuthPersistenceError"]
            | components["schemas"]["AuthPersistenceError"];
        };
      };
    };
  };
  "authSession.refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: components["schemas"]["AuthUser"];
          };
        };
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description UnauthorizedError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedError"];
        };
      };
      /** @description AuthPersistenceError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["AuthPersistenceError"]
            | components["schemas"]["AuthPersistenceError"];
        };
      };
    };
  };
  "authSession.pendingJobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description PendingPersistedJobCounts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PendingPersistedJobCounts"];
        };
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description UnauthorizedError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedError"];
        };
      };
      /** @description PermissionDeniedError */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PermissionDeniedError"];
        };
      };
      /** @description AuthPersistenceError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthPersistenceError"];
        };
      };
      /** @description DatabaseUnavailableError */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DatabaseUnavailableError"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            status: "ok";
          };
        };
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "labels.listLabels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Label"][];
        };
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description UnauthorizedError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedError"];
        };
      };
      /** @description LabelPersistenceError | AuthPersistenceError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["LabelPersistenceError"]
            | components["schemas"]["AuthPersistenceError"];
        };
      };
    };
  };
  "labels.createLabel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name: string & (unknown & unknown);
          prompt?: string | null;
          examples?: ((string & unknown)[] & unknown) | null;
        };
      };
    };
    responses: {
      /** @description Label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Label"];
        };
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description UnauthorizedError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedError"];
        };
      };
      /** @description PermissionDeniedError */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PermissionDeniedError"];
        };
      };
      /** @description LabelAlreadyExistsError */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabelAlreadyExistsError"];
        };
      };
      /** @description LabelPersistenceError | InboxPersistenceError | AuthPersistenceError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["LabelPersistenceError"]
            | components["schemas"]["InboxPersistenceError"]
            | components["schemas"]["AuthPersistenceError"];
        };
      };
      /** @description DatabaseUnavailableError */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DatabaseUnavailableError"];
        };
      };
    };
  };
  "labels.updateLabel": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string & unknown;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          isActive: boolean;
        };
      };
    };
    responses: {
      /** @description Label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Label"];
        };
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description UnauthorizedError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedError"];
        };
      };
      /** @description PermissionDeniedError */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PermissionDeniedError"];
        };
      };
      /** @description LabelNotFoundError */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabelNotFoundError"];
        };
      };
      /** @description LabelPersistenceError | InboxPersistenceError | AuthPersistenceError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["LabelPersistenceError"]
            | components["schemas"]["InboxPersistenceError"]
            | components["schemas"]["AuthPersistenceError"];
        };
      };
      /** @description DatabaseUnavailableError */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DatabaseUnavailableError"];
        };
      };
    };
  };
  "threads.listThreads": {
    parameters: {
      query?: {
        limit?: string | null;
        offset?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description InboxThreadListPage */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InboxThreadListPage"];
        };
      };
      /** @description BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description UnauthorizedError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedError"];
        };
      };
      /** @description InboxPersistenceError | AuthPersistenceError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["InboxPersistenceError"]
            | components["schemas"]["AuthPersistenceError"];
        };
      };
    };
  };
  "threads.syncThreads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description <No Content> */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description InboxNotConnectedError | BadRequest */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InboxNotConnectedError"];
        };
      };
      /** @description InboxReauthorizationRequiredError | UnauthorizedError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["InboxReauthorizationRequiredError"]
            | components["schemas"]["UnauthorizedError"];
        };
      };
      /** @description InboxPersistenceError | AuthPersistenceError */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["InboxPersistenceError"]
            | components["schemas"]["AuthPersistenceError"]
            | components["schemas"]["AuthPersistenceError"];
        };
      };
      /** @description InboxSyncError */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InboxSyncError"];
        };
      };
    };
  };
}
